### ISSUE TITLE
backbone_cli readme.md is outdated

### ISSUE THREAD

**Issue by osaxma** [mtwichel/backbone#15]
I'm following the instructions here:
https://github.com/mtwichel/backbone/tree/main/packages/backbone_cli

I ran `dart pub global activate backbone` and  it was successfully installed (version `0.0.1-dev.13`) but when I run any `backbone` command I get: 
```
zsh: command not found: backbone
```

I tried running the command as follow but also got an error:

```
[~] dart pub global run backbone help
     Could not find bin/backbone.dart in package backbone.
```

--- 
Side note:
The link for the open api example in backbone_cli readme is broken, it should be: 
https://github.com/mtwichel/backbone/blob/main/packages/backbone_cli/example/openapi.yaml

**Comment by osaxma** [comment]
btw, I'm using `Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "macos_x64"`

**Comment by osaxma** [comment]
never mind, I should've followed the readme on the top .. The following command worked:

```
dart pub global activate backbone_cli
```

I would leave this as an issue with the `backbone_cli` readme. 

update: the link for the open api example is also broken in the main readme.

**Comment by osaxma** [comment]
Works great! one issue: the backend package did not have a `pubspec.yaml` file.

**Comment by mtwichel** [comment]
The @osaxma, thanks for trying the package out! It sounds like your issue was resolved, so I'm going to close this issue.
